-- CreateEnum
CREATE TYPE "SexoEstudiante" AS ENUM ('MASCULINO', 'FEMENINO');

-- CreateEnum
CREATE TYPE "ViveConTipo" AS ENUM ('AMBOS_PADRES', 'MADRE', 'PADRE', 'TUTOR', 'OTRO');

-- CreateEnum
CREATE TYPE "PlanPago" AS ENUM ('PAGO_UNICO', 'DOS_PAGOS', 'DIEZ_CUOTAS');

-- CreateEnum
CREATE TYPE "TipoEscolaridad" AS ENUM ('SOLO_ESCOLARIDAD', 'ESCOLARIDAD_ALMUERZO', 'ESCOLARIDAD_ALMUERZO_HORARIO_EXTENDIDO');

-- AlterTable
ALTER TABLE "SolicitudInscripcion" ADD COLUMN     "aceptaReglamento" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "alergias" TEXT,
ADD COLUMN     "anioActa" TEXT,
ADD COLUMN     "apellidoMadre" TEXT,
ADD COLUMN     "apellidoPadre" TEXT,
ADD COLUMN     "autorizaAtencionMedica" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autorizaUsoImagenes" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "cedulaMadre" TEXT,
ADD COLUMN     "cedulaPadre" TEXT,
ADD COLUMN     "celularEstudiante" TEXT,
ADD COLUMN     "celularMadre" TEXT,
ADD COLUMN     "celularPadre" TEXT,
ADD COLUMN     "colegioProcedencia" TEXT,
ADD COLUMN     "dificultadAprendizaje" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dificultadConducta" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "dificultadDiscapacidad" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "direccionEstudiante" TEXT,
ADD COLUMN     "docActaNacimiento" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "docCedulaPadres" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "docCertificadoMedico" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "docRecordNotas" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "docTarjetaVacunacion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emergenciaApellido" TEXT,
ADD COLUMN     "emergenciaCedula" TEXT,
ADD COLUMN     "emergenciaCelular" TEXT,
ADD COLUMN     "emergenciaNombre" TEXT,
ADD COLUMN     "emergenciaParentesco" TEXT,
ADD COLUMN     "emergenciaTelefono" TEXT,
ADD COLUMN     "esNuevoIngreso" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "especifiqueDificultad" TEXT,
ADD COLUMN     "especifiqueEnfermedad" TEXT,
ADD COLUMN     "especifiqueProcedimiento" TEXT,
ADD COLUMN     "fechaEvaluacion" TIMESTAMP(3),
ADD COLUMN     "folioActa" TEXT,
ADD COLUMN     "fotoUrl" TEXT,
ADD COLUMN     "libroActa" TEXT,
ADD COLUMN     "lugarNacimiento" TEXT,
ADD COLUMN     "medicamentos" TEXT,
ADD COLUMN     "motivoCambioColegio" TEXT,
ADD COLUMN     "nacionalidad" TEXT,
ADD COLUMN     "nombreMadre" TEXT,
ADD COLUMN     "nombrePadre" TEXT,
ADD COLUMN     "numeroActa" TEXT,
ADD COLUMN     "numeroHermanos" TEXT,
ADD COLUMN     "oficialiaActa" TEXT,
ADD COLUMN     "padeceEnfermedad" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "personasAutorizadasRetirar" TEXT,
ADD COLUMN     "planPago" "PlanPago",
ADD COLUMN     "profesionMadre" TEXT,
ADD COLUMN     "profesionPadre" TEXT,
ADD COLUMN     "referencia1Nombre" TEXT,
ADD COLUMN     "referencia1Telefono" TEXT,
ADD COLUMN     "referencia2Nombre" TEXT,
ADD COLUMN     "referencia2Telefono" TEXT,
ADD COLUMN     "relacionContacto" "ParentescoTipo",
ADD COLUMN     "religion" TEXT,
ADD COLUMN     "seguroMedico" TEXT,
ADD COLUMN     "sexo" "SexoEstudiante",
ADD COLUMN     "siguiendoProcedimientoMedico" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "telefonoEstudiante" TEXT,
ADD COLUMN     "telefonoMadre" TEXT,
ADD COLUMN     "telefonoPadre" TEXT,
ADD COLUMN     "telefonoTrabajoMadre" TEXT,
ADD COLUMN     "telefonoTrabajoPadre" TEXT,
ADD COLUMN     "tieneDificultad" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tieneHermanosEnColegio" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tipoEscolaridad" "TipoEscolaridad",
ADD COLUMN     "tipoSangre" TEXT,
ADD COLUMN     "tutorLegalApellido" TEXT,
ADD COLUMN     "tutorLegalCedula" TEXT,
ADD COLUMN     "tutorLegalNombre" TEXT,
ADD COLUMN     "tutorLegalParentesco" TEXT,
ADD COLUMN     "tutorLegalTelefono" TEXT,
ADD COLUMN     "ultimoGradoCursado" TEXT,
ADD COLUMN     "viveCon" "ViveConTipo";
